dbtlearn:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: WGNPVQM-BI98485
      user: GURURAJ
      password: Gururaj!@34
      role:  SYSADMIN
      database:  TEST_SCHEMACHANGE
      warehouse:  COMPUTE_WH
      schema: RAW
