name: Triggered dbt test

on:
  push:
    branches:
      - main

env:
  DBT_PROFILES_DIR: ./
  SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
  SF_USERNAME: ${{ secrets.SF_USERNAME }}
  SF_ROLE: ${{ secrets.SF_ROLE }}
  SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
  SF_DATABASE: ${{ secrets.SF_DATABASE }}
  SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}
jobs:
  dbt_run_test:
    name: dbt test
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9.x"

      - name: Install dependencies
        run: |
          pip install dbt-snowflake

      - name: Run test
        run: dbt test
        working-directory: ./
